import axios, { AxiosError } from 'axios'

export const api = axios.create({
  baseURL: process.env.NEXT_PUBLIC_BASE_URL,
})

export const DEFAULT_ERROR_MESSAGES = {
  networkError: 'üì° Network error, please try again later.',
} as const

// Intercptando os erros e tratando eles
api.interceptors.response.use(
  (response) => response,
  (error: AxiosError<any>) => {
    if (error.code === AxiosError.ERR_NETWORK) {
      error.message = DEFAULT_ERROR_MESSAGES.networkError
      return Promise.reject(error)
    }

    if (error.response && error.response.status === 403) {
      // Forbidden
      error.message =
        'API sofreu muitas requisi√ß√µes de uma vez, aguarde alguns minutos para fazer uma nova requisi√ß√£o'
      return Promise.reject(error)
    }

    if (error.response && error.response.status === 404) {
      // User not found
      error.message = 'Usu√°rio n√£o encontrado'
      return Promise.reject(error)
    }
  },
)
